FROM node:18-alpine3.16 as base

# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat
RUN apk update

# Set working directory
WORKDIR /app

RUN yarn global add turbo
COPY . .

ARG appScope
RUN \
  if [[ -z "$appScope" ]] ; \
  then echo "appScope argument not provided" && false ; \
  else echo "Containerfile configured for $appScope" ; \
  fi

RUN turbo prune --scope=${appScope} --docker

FROM node:18-alpine3.16 as builder
WORKDIR /app
RUN corepack enable

COPY .gitignore .gitignore

COPY --from=base /app/out/json/ .
COPY --from=base /app/out/pnpm-*.yaml ./

RUN pnpm install --frozen-lockfile

# Build the app
COPY --from=base /app/out/full/ .
RUN pnpm turbo run build

FROM node:18-alpine3.16 as runner
WORKDIR /app
ARG appScope

# Don't run production as root
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 service-user
USER service-user

ENV NODE_ENV production

COPY --from=base /app/apps/backend/package.json .
COPY --from=base /app/node_modules ./node_modules
COPY --from=builder /app/apps/backend/dist ./dist

CMD ["node", "dist/main.js"]