name: Workflow

on:
  push:
    branches:
      - main
      - '[0-9]+.x'
      - epic/3-mvp
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn lint

      - name: Format
        run: yarn format:check

      - name: Test
        run: yarn test --passWithNoTests

      - name: Build
        run: yarn build
  
  deploy:
    uses: getbranches/conf/.github/workflows/deploy-to-cloud-run.yaml@epic-first-install
    with:
      docker-registry: ${{ inputs.DOCKER_REPOSITORY }}
      google-project-id: ${{ secrets.GOOGLE_PROJECT_ID }}
      workload-identity-provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
      service-account-email: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
      self-url: https://missing.com/
      log-level: debug